name: Start
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run multi command
        run: |
          git clone https://github.com/amo-yotakenoko/VirtualRobot_Scratch.git
          echo -----
          ls
          echo -----
          cd VirtualRobot_Scratch
          echo -----
          ls
          echo -----
          cd scratch-gui
          echo -----
          ls
          echo -----
          npm start
