name: Start
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run multi command
        run: |
          git clone https://github.com/amo-yotakenoko/VirtualRobot_Scratch.git

          ls
          cd scratch-gui
          ls
          npm run build
