name: Start
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run multi command
        run: |
          pwd
          ls
          mkdir mk
          ls
          cd mk
          pwd
