name: GithubActoinsTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello-World
        env:
          run: echo "HELLO-echo2"
        run: |
          echo $PRINT
